name: dart_cms
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  sqflite_common_ffi: ^2.3.5
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.32
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
