// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDop8IXg_l4lSulYG849Sv8G6kofUJdGAs',
    appId: '1:421547517986:web:1aa4f9b2083c72a0ab427b',
    messagingSenderId: '421547517986',
    projectId: 'group-splitter',
    authDomain: 'group-splitter.firebaseapp.com',
    databaseURL: 'https://group-splitter-default-rtdb.firebaseio.com',
    storageBucket: 'group-splitter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzd_aHwH50YtMZvh-DY0VpDEnKk7fg0Cs',
    appId: '1:421547517986:android:8cef4c96753f8cedab427b',
    messagingSenderId: '421547517986',
    projectId: 'group-splitter',
    databaseURL: 'https://group-splitter-default-rtdb.firebaseio.com',
    storageBucket: 'group-splitter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq09-p_v56n3YX96SeKTzzlID3hGzHeLg',
    appId: '1:421547517986:ios:499bb2a670c301b9ab427b',
    messagingSenderId: '421547517986',
    projectId: 'group-splitter',
    databaseURL: 'https://group-splitter-default-rtdb.firebaseio.com',
    storageBucket: 'group-splitter.firebasestorage.app',
    iosBundleId: 'com.example.smartSplitFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq09-p_v56n3YX96SeKTzzlID3hGzHeLg',
    appId: '1:421547517986:ios:499bb2a670c301b9ab427b',
    messagingSenderId: '421547517986',
    projectId: 'group-splitter',
    databaseURL: 'https://group-splitter-default-rtdb.firebaseio.com',
    storageBucket: 'group-splitter.firebasestorage.app',
    iosBundleId: 'com.example.smartSplitFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDop8IXg_l4lSulYG849Sv8G6kofUJdGAs',
    appId: '1:421547517986:web:eb2e9abf29c6e6f0ab427b',
    messagingSenderId: '421547517986',
    projectId: 'group-splitter',
    authDomain: 'group-splitter.firebaseapp.com',
    databaseURL: 'https://group-splitter-default-rtdb.firebaseio.com',
    storageBucket: 'group-splitter.firebasestorage.app',
  );
}
